### ISSUE TITLE
Multiple File Uploads

### ISSUE THREAD

**Issue by jameson-m** [bleutzinn/grav-plugin-add-page-by-form#29]
For some reason when I drag and drop multiple files for upload only the first file is being uploaded and saved to '@self'. At other times, the second or third, or the second and third files are being uploaded only. It does not seem to be specific to just one file type. In the frontmatter I've included multiple: true. Also, when I include the limit in the frontmatter and set it to 0 or 10, no files are uploaded (both when attempting to upload single and multiple files).

Is this a known issue? I can't for the life of me figure out why it won't upload more than one file consistently.

**Comment by bleutzinn** [comment]
Could you please specify which version of Grav and which version of the Form plugin you are using?
That will help me in trying to reproduce this and hunt down the problem. Also I would like to know whether this problem only occurs when uploading by Drag and Drop or when selecting files through the filesystem browse dialog as well?

**Comment by jameson-m** [comment]
The issue occurs both when dragging and dropping files and when selecting through the filesystem. I am running Grav version 1.3.3 and Form version 2.9.0. Looks like there are two fairly recent updates to both. Would you like for me to try updating both first and see if I can still replicate?

**Comment by bleutzinn** [comment]
Please have a go with the version in the ["upload-fix" branch](https://github.com/bleutzinn/grav-plugin-add-page-by-form/tree/upload-fix) and let me know your findings.

**Comment by jameson-m** [comment]
Still doesn't quite work completely. I noticed that if I uploaded multiple files of different types (both drag and drop and click to add), in this case pdf and jpg/png, only one of the files would be uploaded. If I uploaded all pdf files or all image (jpg/png) files, all seemed to upload just fine.

Clicking the upload box to add files seemed to produce some very spotty results. A couple times it uploaded more than just one file (never seemed to upload more than 2), but it usually just uploaded one file. It didn't seem to necessarily upload the first file added to the list either -- seemed very random which one was chosen.

I can't think of any reason on my end why it won't work. In the frontmatter of my form page i have listed application/pdf and 'image/*' listed as accepted file types.

**Comment by bleutzinn** [comment]
The Form plugin uses a two phase process to upload files. After the progress meter has finished and the checkbox is shown per uploaded file the actual files have been uploaded to the server. They then temporarily reside in the `/tmp/uploaded_files` directory.

To make sure that part is functioning properly you can check the existence of your files in that location. They are renamed but the type and the size should be sufficient to determine they are the ones you uploaded.

Once the form is submitted, phase two is entered. Normally, that is without the Add Page plugin, the Form plugin moves the uploaded files to their final destination. When the destination in the form is set to `@self` the Add Page plugin 'hijacks' this action and moves the files from their temporary location to the folder of the new page.

If you can confirm that your uploaded files are saved correctly to the temporary location then for sure the problem lies in the handling of the file move in my plugin.

BTW I'm using the same versions for testing.

**Comment by jameson-m** [comment]
Thanks for the explanation of how that process works. I tested uploading some files, and noticed some inconsistencies in potentially both the Form and Add Page By Form plugins.

When uploading multiple copies of the same file of PDF type, they all appear within the tmp/uploaded-files folder as separate and unique files. Upon submitting the form, only one of the copies of the file is actually submitted and added to the new page. I'm not sure why someone would want to upload multiple copies of the same file, but I did notice it seemed to break it. This could just be my own testing error.

The other issue I noticed seems potentially to be more related to the Form plugin. When uploading image files (png or jpg), I couldn't reliably get all images to upload to the `tmp/uploaded-files` directory. I'm assuming this is something to report to the Form plugin since Add Page By Form only deals with the data once it's been properly uploaded to the `tmp/uploaded-files` directory?

**Comment by bleutzinn** [comment]
I think I can explain what happens when you upload the same file more than once. Although the Form plugin does upload each file and saves each file with a temporary filename, it also registers the original filename. When moving the uploaded files it uses the original filename to rename each file from it's temporary name into it's original name. In doing so it effectively overwrites any file with that original name which in the end results in just a single file.

I did some extensive testing and I'm able, both on localhost and on a live server, to upload a set of files of different (mime) types. Every file is saved alongside the new page content in the new page's folder.

To rule out any possible issues in the Add Page plugin I suggest you disable it and do some more tests. One thing to take care is that when something goes wrong the temporary directory is not (always) emptied which may result in strange behaviour in subsequent tests.

**Comment by jameson-m** [comment]
Sounds like it must be a flaw in my testing and/or some sort of issue with the Files plugin on my end. I will do some testing in the next few days to see if I can get it to work correctly. I'm fine with closing this since you were unable to replicate the issue. If I think it's more related to the add-page-by-form plugin, I will then re-open it. Thanks again for the help!
