### ISSUE TITLE
other integration besides markdown

### ISSUE THREAD

**Issue by mikulabc** [bleutzinn/grav-plugin-add-page-by-form#38]
i was wondering how i could integrate the [https://github.com/newbthenewbd/grav-plugin-tinymce-editor/blob/develop/README.md](https://github.com/newbthenewbd/grav-plugin-tinymce-editor/blob/develop/README.md)

instead of the SimpleMDE Markdown Editor.

thanks :)

**Comment by bleutzinn** [comment]
Before even trying I would advice you to think about the consequences of mixing the HTML output of TinyMCE with your other content in Grav which is in Markdown. Mixing HTML with Markdown is allowed and supported in Grav but it may hinder further processing.

Another approach is to convert HTML to Markdown but because of the limited set of markup elements of Markdown compared to HTML you must be selective which markup and thus tool buttons will be useful in TinyMCE.

On how to integrate TinyMCE in my Add Page plugin I can't advice you before diving in myself, which I say beforehand I do not intend to do.
